@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-right-> "1" AllExamsList
AllExamsList -[hidden]down- UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person
AllExamsList -right-> Exams

Person -up-> "*" Tag
Person -up-> "*" Exams

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> Subject
Person *--> "1" LogList
Person *--> Payment

LogList -down-> "*" Log

@enduml
