@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ViewCommandParser" as ViewCommandParser LOGIC_COLOR
participant "v:StatCommand" as StatCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
participant "p:IsSameIdPredicate" as IsSameIdPredicate LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("view -stats")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("view -stats")
activate AddressBookParser

create ViewCommandParser
AddressBookParser -> ViewCommandParser
activate ViewCommandParser

ViewCommandParser --> AddressBookParser
deactivate ViewCommandParser

AddressBookParser -> ViewCommandParser : parse("-stats")
activate ViewCommandParser

ViewCommandParser -> ViewCommandParser : arePrefixesPresent(argsMultimap, "all")

ViewCommandParser -> ViewCommandParser : arePrefixesPresent(argsMultimap, "name")

ViewCommandParser -> ViewCommandParser : arePrefixesPresent(argsMultimap, "id")

create StatCommand
ViewCommandParser -> StatCommand : StatCommand()
activate StatCommand

StatCommand -->  ViewCommandParser : v
deactivate StatCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewCommandParser -[hidden]-> AddressBookParser
destroy StatCommand

ViewCommandParser --> AddressBookParser : v
deactivate ViewCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewCommandParser -[hidden]-> AddressBookParser
destroy ViewCommandParser

AddressBookParser --> LogicManager : v
deactivate AddressBookParser

LogicManager -> ViewCommand : execute(v)
activate ViewCommand

create CommandResult
ViewCommand -> CommandResult : CommandResult(MESSAGE_SUCCESS, null, false, false, true, false);
activate CommandResult

CommandResult --> ViewCommand
deactivate CommandResult

ViewCommand --> LogicManager : r
deactivate ViewCommand

[<--LogicManager
deactivate LogicManager
@enduml
